### ISSUE TITLE
プルダウンメニューの並び順について

### ISSUE THREAD

**Issue by TakashiObo** [code4fukui/fukui-kanko-stat#11]
①都道府県　北からエリア順又は五十音順。
②性別　無回答を最下部に他はセンシティブなイシューなのでこだわりはありません。
③６分類　北東から南西順に並べる。※定義の嶺南東部と嶺南西部が直感的にはわかりにくいので嶺南東部（若狭町以東）、嶺南西部（小浜市以西）などの表記は可能でしょうか。
④世帯年収　少～多または多～少順。
⑤満足度　とても満足、満足、どちらでもない、不満、とても不満の順。
⑥NPS　０→１０または１０→０順。
⑦今後の来訪意向　また行きたい、機会があれば・・・、どちらともいえない、あまり・・・、行きたくない、福井県在住
⑧同行者　選択肢以外の回答はその他にまとめたい。
昇順降順の並べ替えも将来的には可能になると便利ですね。

**Comment by EiichiMiyagawa** [comment]
@TakashiObo 
> ⑧同行者　選択肢以外の回答はその他にまとめたい。

同行者の選択肢はどちらになりますでしょうか？

**Comment by TakashiObo** [comment]
> @TakashiObo
> 
> > ⑧同行者　選択肢以外の回答はその他にまとめたい。
> 
> 同行者の選択肢はどちらになりますでしょうか？

basicmathのページを拝見すると、その他に統合していただいているようです。
