### ISSUE TITLE
円グラフにタイトルをいれてほしい

### ISSUE THREAD

**Issue by NaobumiTanaka** [code4fukui/fukui-kanko-stat#13]
それぞれの円グラフの上部にそれぞれグラフのタイトルをいれた方が見やすいかと思いました。
都道府県、年代、性別、6分類→ここは回答エリア（6分類）？、回答エリア2→回答エリア（詳細）、世帯年収、回答月、満足度、不便さ、NPS、10、宿泊数（県内）、今後の来訪意向、同行者

**Comment by taisukef** [comment]
タイトル、追記しました
https://github.com/code4fukui/fukui-kanko-stat/commit/783e2f509e8d8895f672f47d79714846a16bc76e
