### ISSUE TITLE
各オープンデータを回遊できるようにしたい

### ISSUE THREAD

**Issue by NaobumiTanaka** [code4fukui/fukui-kanko-stat#14]
以下にあるそれぞれのオープンデータの掲載ページをページ上部にあるグローバルヘッダみたいな感じで回遊できるようにしてほしい。
（今後追加されるものも）

観光オープンデータ簡易分析
観光オープンデータ簡易分析(福井県外からの来訪者)  
福井観光エリア満足度ランキング
観光オープンデータ簡易分析(福井県外からの来訪者)

**Comment by taisukef** [comment]
対応しました
https://code4fukui.github.io/fukui-kanko-stat/
