### ISSUE TITLE
福井県アンケートコメントマップで地名検索をできるようにしてほしい

### ISSUE THREAD

**Issue by NaobumiTanaka** [code4fukui/fukui-kanko-stat#15]
福井県アンケートコメントマップで地名検索をできるようにしてほしい。
地図をズームしたり移動するのに少し時間がかかるので、ダイレクトにその周辺のエリアに飛べたら利便性が高まるなと思いました。
https://code4fukui.github.io/sightseeingApp/

**Comment by taisukef** [comment]
対応しました！
