### ISSUE TITLE
アンケートデータ・デザイン案

### ISSUE THREAD

**Issue by NaobumiTanaka** [code4fukui/fukui-kanko-stat#18]
アンケートデータ・デザイン案を作ってみましたこちらでいかがでしょうか？
[アンケートデータ・デザイン案](https://drive.google.com/drive/folders/1sDrJJd3Xbj0CAcOFiz90zyyPR_dKs5pI)
[イメージボード](https://drive.google.com/drive/folders/1sDrJJd3Xbj0CAcOFiz90zyyPR_dKs5pI)

**Comment by taisukef** [comment]
ステキデザイン、転記しました
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/1715217/193806487-ed2a4de6-86e0-48a9-bcc3-5e8c73fe1415.png">

**Comment by taisukef** [comment]
スマホではどのように見せますか？

**Comment by taisukef** [comment]
イメージボード
<img width="498" alt="image" src="https://user-images.githubusercontent.com/1715217/193808214-2c9b8fd7-050e-46d0-9eb9-a3bc9a6c654d.png">

**Comment by NaobumiTanaka** [comment]
> スマホではどのように見せますか？

そのあたりの詳細案はこれから作り込んでいく感じですー！

**Comment by taisukef** [comment]
円グラフ、近い感じに変更しました
https://code4fukui.github.io/fukui-kanko-stat/

変更点
https://github.com/code4fukui/fukui-kanko-stat/commit/f1cc1ec58ec55ae1379fdca5b63f243e194574de

**Comment by taisukef** [comment]
スマホでの表示、調整必要
