### ISSUE TITLE
年代や世帯年収などは棒グラフにしたい

### ISSUE THREAD

**Issue by taisukef** [code4fukui/fukui-kanko-stat#19]
データ種に合わせた表現にすると良さそう
Thanks > @h_okumura さん
https://twitter.com/h_okumura/status/1580377959688728576

**Comment by EiichiMiyagawa** [comment]
@taisukef 
こちら、対象のデータは円グラフを完全にやめて棒グラフに変更してしまう認識でよろしいでしょうか？
