### ISSUE TITLE
福井県が好きな都道府県ランキングを作りたい

### ISSUE THREAD

**Issue by taisukef** [code4fukui/fukui-kanko-stat#2]
どの都道府県の人が満足度が高いか？

**Comment by EiichiMiyagawa** [comment]
@taisukef 
こちらの機能を作成するためのオープンデータは現時点で用意されていますでしょうか？
また、こちらの機能は別ページを作成するという認識でよろしいでしょうか？

**Comment by taisukef** [comment]
観光アンケートオープンデータを使って、別ページのアプリで作成のイメージ
