### ISSUE TITLE
滞在時間推定をグラフ化したい

### ISSUE THREAD

**Issue by taisukef** [code4fukui/fukui-kanko-stat#3]
伸ばしていきたい観光客あたりの滞在時間をグラフ化したい

**Comment by EiichiMiyagawa** [comment]
@taisukef
こちらの機能を作成するためのオープンデータは現時点で用意されていますでしょうか？
また、こちらの機能は別ページを作成するという認識でよろしいでしょうか？

**Comment by taisukef** [comment]
アンケートオープンデータの宿泊数をベースにした別ページのイメージ
