### ISSUE TITLE
棒グラフの色を変更してほしい

### ISSUE THREAD

**Issue by NaobumiTanaka** [code4fukui/fukui-kanko-stat#58]
棒グラフの色が全体のトーンからはずれているので、円グラフの福井県の色

rgb(163,187,188)

への変更、ご検討お願いします！

**Comment by EiichiMiyagawa** [comment]
@NaobumiTanaka 
棒グラフの色の調整を行いました。

**Comment by NaobumiTanaka** [comment]
確認しましたー、違和感がなく良い感じです。お忙しいん中ありがとうございました！
