### ISSUE TITLE
コメントマップ上部に回遊できるリンクを

### ISSUE THREAD

**Issue by NaobumiTanaka** [code4fukui/fukui-kanko-stat#59]
コメントマップ上部には他の同ページにあるグローバルヘッダ（回遊できるリンク）がないので、設定していただけたらです

https://code4fukui.github.io/sightseeingApp/

**Comment by EiichiMiyagawa** [comment]
@NaobumiTanaka 
全ての画面にヘッダが表示されるよう修正しました。
（元々は表示されていたのですが、私が手を加えていたため非表示の状態になっていたようです。。。）
