### ISSUE TITLE
折れ線グラフ

### ISSUE THREAD

**Issue by TakashiObo** [code4fukui/fukui-kanko-stat#6]
時系列データでトレンドをみられないでしょうか。

**Comment by taisukef** [comment]
まずはどんなトレンドが見えるといいでしょうか？

**Comment by TakashiObo** [comment]
満足度とNPSの数値のトレンドが見えるとありがたいです。

**Comment by EiichiMiyagawa** [comment]
@taisukef
cc: @TakashiObo 
こちらの機能は別ページを作成するという認識でよろしいでしょうか？

**Comment by taisukef** [comment]
福井県観光アンケートトレンド、追加されました！ @TakashiObo 
https://code4fukui.github.io/fukui-kanko-stat/trend.html
