### ISSUE TITLE
宿泊施設グラフのデフォルト設定値

### ISSUE THREAD

**Issue by NaobumiTanaka** [code4fukui/fukui-kanko-stat#60]
宿泊施設グラフのデフォルト設定値が2021/7-2018/1となっていて、ページ訪問時は真っ白なので、何かしらグラフがでてるように
2021/7-2021/12 などと初期設定されておいた方がいいと思いました。

対象ページ
https://eiichimiyagawa.github.io/accommodations-graph/

**Comment by EiichiMiyagawa** [comment]
@NaobumiTanaka 
2018/01 - 2021/12 に初期値を設定するよう修正しました。

**Comment by NaobumiTanaka** [comment]
ありがとうございます！確認いたしましたー。
