### ISSUE TITLE
ドロップダウンリストの複数選択

### ISSUE THREAD

**Issue by TakashiObo** [code4fukui/fukui-kanko-stat#7]
ドロップダウンリストについて複数選択できるようにならないか。たとえば年収５００万円以上を選択したい場合、複数選択できないとそのレンジのみのデータとなる。また、N数が足りない場合や首都圏という括りでデータ抽出ができると助かります。

**Comment by EiichiMiyagawa** [comment]
@taisukef 
こちらの複数選択機能はselectタグのmultipleオプションを設定するだけで良いでしょうか？
（PCだとCtrlキーを押しながら選択などの操作が必要となる）
もしくは、何かライブラリなどを使用する必要があるでしょうか？

**Comment by taisukef** [comment]
multipleオプションでまずつくるかたちでいきましょう
