### ISSUE TITLE
観光オープンデータ簡易分析　修正依頼

### ISSUE THREAD

**Issue by MasanoriSatake** [code4fukui/fukui-kanko-stat#74]
[観光オープンデータ簡易分析](https://code4fukui.github.io/fukui-kanko-stat/)

１）回答エリア　が　先祖帰りしていると思われます。（2022年度のエリアでかつ、池田町が抜けている状態になっている）

２）回答月が、3月　のみの表示になっており他の月でもソート出来るように戻して頂けるとありがたいです。可能であれば、2022年4月から1ヶ月毎の表示機能もあるとありがたいです。

よろしくお願いします。

**Comment by taisukef** [comment]
エリア名、回答月、修正しました
