### ISSUE TITLE
アンケートコメント　マップ　評価の満足度（色）ごとにソートしたい

### ISSUE THREAD

**Issue by NaobumiTanaka** [code4fukui/fukui-kanko-stat#9]
アンケートコメントマップ　評価数が多くなるとピンがふえてきて大変なので、評価の満足度（色）ごとにソートできたら素敵です。
たとえば不満は赤になっておりますが、赤だけを選択して表示できるようにするとか。

**Comment by taisukef** [comment]
満足度毎の表示・非表示に対応しました
https://code4fukui.github.io/sightseeingApp/
